
MUTATION_RATE = 10
DEBUG_ENABLED = False
if DEBUG_ENABLED: DARKLET = "  |  DEBUG ENABLED"
else: DARKLET = ""
WIDTH, HEIGHT = 1280*1.25, 720*1.25
FOOD_AMOUNT = 60
FONT_PREFERENCES = ["consolas", "menlo", "monaco", "couriernew"]
VERSION_NAME = "alpha"
VERSION = "1.0"